import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { clashDisplay } from "./fonts";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} relative antialiased`}>
        {/* GLOBAL BACKGROUND LAYER */}
        <div className="global-bg" />

        {/* OPTIONAL: GLOBAL VIGNETTE */}
        <div className="global-vignette" />
        <SmoothScrollProvider>
          <Navigation />
          {children}
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
