import type { Metadata } from "next";
import "./globals.css";
import { ReactLenis } from "../utils/lenis";
import Navigation from "@/components/Navigation";
import { clashDisplay } from "./fonts";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} antialiased`}>
        <Navigation />
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
